sudo: false
language: python
notifications:
  email: false
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.9
    - python: 3.5
      env: DJANGO_VERSION=1.7.8
    - python: 3.5
      env: DJANGO_VERSION=1.8.2
before_install:
  - pip install Django==$DJANGO_VERSION
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt || pip install --upgrade "setuptools" "pip==7.1"
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov
